// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_BEJgbSgWIR9trO92QbNBYpEfN5CaR6A',
    appId: '1:953836778191:web:d654c70bd88d7549efbdba',
    messagingSenderId: '953836778191',
    projectId: 'quizz00',
    authDomain: 'quizz00.firebaseapp.com',
    storageBucket: 'quizz00.appspot.com',
    measurementId: 'G-8FT4MPV2TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJN8rwtW30aSrGlRB7Ro5hql_ttPPSsHQ',
    appId: '1:953836778191:android:14677ccc81dc0bf7efbdba',
    messagingSenderId: '953836778191',
    projectId: 'quizz00',
    storageBucket: 'quizz00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRuAMpHLqnhfTHuSFQvQzQM9W_0mkNnu4',
    appId: '1:953836778191:ios:27b9d91c9343940befbdba',
    messagingSenderId: '953836778191',
    projectId: 'quizz00',
    storageBucket: 'quizz00.appspot.com',
    iosBundleId: 'com.example.quizzApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRuAMpHLqnhfTHuSFQvQzQM9W_0mkNnu4',
    appId: '1:953836778191:ios:27b9d91c9343940befbdba',
    messagingSenderId: '953836778191',
    projectId: 'quizz00',
    storageBucket: 'quizz00.appspot.com',
    iosBundleId: 'com.example.quizzApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_BEJgbSgWIR9trO92QbNBYpEfN5CaR6A',
    appId: '1:953836778191:web:ca154fc1e1f9af17efbdba',
    messagingSenderId: '953836778191',
    projectId: 'quizz00',
    authDomain: 'quizz00.firebaseapp.com',
    storageBucket: 'quizz00.appspot.com',
    measurementId: 'G-YH0N6QXDMX',
  );
}
